# Toeplitz Matrix
In the following project, we will input two vectors of same size and make a [toeplitz matrix](https://en.wikipedia.org/wiki/Toeplitz_matrix) by them in the following format:

```
c = [c1, c2, ..., cn]
v = [v1, v2, ..., vn]

Toeplitz_Matriz(c, v) = [
    [c1, r2, r3, ..., rn],
    [c2, c1, r2, ..., r(n-1)],
    ...
    [cn, c(n-1), ..., c1]
]
```

## Import required libraries

In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

## Get Input and Construct Matrix
By getting two vectors `v`, `c` we can construct the corresponding matrix by iterating over elements in the matrix.

In [14]:
def get_vector_of_size_n(n):
    result = np.zeros([n])
    for i in range(n):
        print(f'Enter the {i + 1}-th element of vector: ', end='')
        result[i] = int(input())
    return result

C = get_vector_of_size_n(5)
V = get_vector_of_size_n(5)
print(C)
print(V)

Enter the 1-th element of vector: 5
Enter the 2-th element of vector: -1
Enter the 3-th element of vector: 0
Enter the 4-th element of vector: 6
Enter the 5-th element of vector: 8
Enter the 1-th element of vector: 12
Enter the 2-th element of vector: 8
Enter the 3-th element of vector: -9
Enter the 4-th element of vector: 4
Enter the 5-th element of vector: -2
[ 5. -1.  0.  6.  8.]
[12.  8. -9.  4. -2.]


In [35]:
def construct_toeplitz_matrix(C, V):
    if C.shape[0] != V.shape[0]:
        raise AssertionError('length of C and V must be the same.')
        
    n = C.shape[0]
    result = np.zeros([n, n])
    for i in range(n):
        for j in range(n):
            if i >= j:
                result[i][j] = C[i - j]
            else:
                result[i][j] = V[j - i]
    return result
toeplitz_matrix = construct_toeplitz_matrix(C, V)
print(toeplitz_matrix)

[[ 5.  8. -9.  4. -2.]
 [-1.  5.  8. -9.  4.]
 [ 0. -1.  5.  8. -9.]
 [ 6.  0. -1.  5.  8.]
 [ 8.  6.  0. -1.  5.]]


## Compute Determinant
Compute an echelon form of the toeplitz matrix and update determinant when using elementary operations.

In [42]:
PRECISION = 

def calculate_determinant_of_matrix(input_matrix):
    A = input_matrix.copy() # to avoid changing the original matrix
    determinant = 1
    n = A.shape[0]
    
    for j in range(n): # the j-th column in j-th row will become a new leading entry
        for i in range(j, n): # find a row with nonzero element in j-th column and swap it with current j-th row
            if A[i][j] != 0:
                for k in range(n):
                    A[i][k], A[j][k] = A[j][k], A[i][k]
                determinant *= -1 # swapping two lines will result in changing the sign of determinant
                break
        if A[j][j] == 0:
            return 0 # there exists a zero element on the main diagonal when computing echelon form
            
        for i in range(j + 1, n): # to make (j, j) element a leading entry, make all below elements zero
            if A[i][j] == 0: # this row doesn't need to be scaled
                continue
                
            # all elements in this row must be multiply by row_coefficient factor and subtracted
            # by element in same column and j-th row. also determinant must be multiplied by 1/row_coefficient
            # because of elementary operation (multiplying one row by some value)
            row_coefficient = A[j][j] / A[i][j]
            determinant /= row_coefficient
            for k in range(n):
                A[i][k] = A[i][k] * row_coefficient - A[j][k]
        
    for i in range(n):
        for j in range(n):
            print(A[i][j].round(6))
    # current matrix is in echelon form
    for i in range(n):
        determinant *= A[i][i]
    return determinant.round(6)

calculate_determinant_of_matrix(toeplitz_matrix)

[[ 5.00000000e+00  8.00000000e+00 -9.00000000e+00  4.00000000e+00
  -2.00000000e+00]
 [ 0.00000000e+00 -3.30000000e+01 -3.10000000e+01  4.10000000e+01
  -1.80000000e+01]
 [ 0.00000000e+00  0.00000000e+00  1.96000000e+02  2.23000000e+02
  -2.79000000e+02]
 [ 0.00000000e+00  0.00000000e+00  2.84217094e-14 -3.45144928e+02
   4.41859903e+02]
 [ 0.00000000e+00  0.00000000e+00 -2.84217094e-14  0.00000000e+00
  -7.92392833e+01]]


-58900.0